language: rust

rust:
    - stable
    - beta
    - nightly

cache: cargo

matrix:
    fast_finish: true
    allow_failures:
        - rust: nightly

before_script:
    - rustup component add rustfmt-preview

env:
    - TEST_DIR=simple-safety

script:
    - if [ "$TRAVIS_RUST_VERSION" == "stable" ]; then make fmt; fi
    - cd $TEST_DIR && cargo build --verbose && cargo test --verbose

